apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-v1
  template:
    metadata:
      labels:
        app: helloworld-v1
    spec:
      containers:
        - name: k8s-demo
          image: arjunachari12/k8s-demo:latest
          ports:
            - name: nodejs-port
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-v1
spec:
  ports:
  - port: 80
    nodeport: 30303
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld-v1
  type: NodePort
